name: Ubuntu Latest JDK 1.8

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: ['1.8']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: Run tests
      run: sbt test
